# Server configuration
server.port=8080
logging.level.org.springframework=DEBUG

# MongoDB configuration
spring.data.mongodb.uri=${MONGO_URI}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# AI
lumi.prompt=${SYSTEM_PROMPT}